name: yt-comment-reply-ai-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - tensorflow>=2.10.0
    - scikit-learn>=1.3.2
    - numpy>=1.24.4
    - pandas>=2.0.3
    - h5py>=3.11.0
    - pillow>=10.4.0
    - keras>=2.10.0
    - tensorboard>=2.10.1
    - customtkinter>=5.2.2
    - pyautogui>=0.9.54
    - pyperclip>=1.9.0
    - keyboard>=0.13.5
    - requests>=2.32.3
    - psutil>=7.0.0
    - darkdetect>=0.8.0
    - mouseinfo>=0.1.3
    - pymsgbox>=1.0.9
    - pygetwindow>=0.0.9
    - pyrect>=0.2.0
    - pyscreeze>=1.0.1
    - pytweening>=1.2.0
    - tkfontawesome>=0.2.0
    - tksvg>=0.7.4